CREATE TABLE "PUBLIC"."F_USER" (
	"ID" VARCHAR(36 char) NOT NULL DEFAULT NULL::BPCHAR,
	"USERNAME" VARCHAR(100 byte) NULL,
	"AGE" INT4 NULL,
	"XGSJ" TIMESTAMP(20) NULL DEFAULT NOW(),
	"CJSJ" TIMESTAMP(20) NULL DEFAULT NOW(),
	"SFRZ" TINYINT NULL
)
WITH (
	OIDS=FALSE
);

CREATE OR REPLACE FUNCTION fuser_stamp() RETURNS trigger AS
BEGIN
NEW.xgsj:= current_timestamp;
RETURN NEW;
END;
CREATE OR REPLACE TRIGGER fuser_stamp BEFORE INSERT OR UPDATE ON "F_USER"
FOR EACH ROW EXECUTE PROCEDURE fuser_stamp();
